# -*- coding: utf-8 -*-
"""从 liuyao_0519.py 提取全部静态数据，生成 web/js/data.js"""
import importlib.util
import json
import sys
import types
from pathlib import Path

# 源文件顶层 import 的第三方库在提取数据时不会真正用到（仅在函数体内引用），
# 用 stub 代替，避免依赖安装。
for name in [
    "numpy", "requests", "PIL", "PIL.Image", "PIL.ImageTk",
    "tkinter", "tkinter.ttk", "tkinter.messagebox", "tkinter.simpledialog",
    "tkinter.filedialog", "tkinter.scrolledtext", "lunardate",
]:
    if name not in sys.modules:
        m = types.ModuleType(name)
        # from X import Y 形式需要子模块同时挂为父模块属性
        parent, _, child = name.rpartition(".")
        if parent and parent in sys.modules:
            setattr(sys.modules[parent], child, m)
        sys.modules[name] = m

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT.parent / "liuyao_0519.py"
OUT = ROOT / "web" / "js" / "data.js"

spec = importlib.util.spec_from_file_location("liuyao", SRC)
mod = importlib.util.module_from_spec(spec)
sys.modules["liuyao"] = mod
spec.loader.exec_module(mod)  # tkinter 仅被 import，不会启动 GUI（main 有 __name__ 守卫）

src = SRC.read_text(encoding="utf-8")


def grab_prompt(mode):
    """从 DeepSeekAnalyzer.analyze_divination 源码提取两段系统提示词"""
    marker = 'if self.mode == "问道":' if mode == "问道" else "else:  # 易康模式"
    i = src.find(marker)
    if i < 0:
        raise RuntimeError(f"未找到模式标记: {mode}")
    j = src.find('system_prompt = """', i) + len('system_prompt = """')
    k = src.find('"""', j)
    return src[j:k]


hex_db = {}
for name, d in mod.HEXAGRAM_DB.items():
    hex_db[name] = {
        "name": d["name"],
        "binary": d["binary"],
        "judgment": d["judgment"],
        "palace": d["palace"],
        "shi_yao": d["shi_yao"],
        "type": d["type"],
        "xinxi": d.get("xinxi", ""),
        "lines": {str(k): v for k, v in d["lines"].items()},
    }

data = {
    "HEXAGRAM_DB": hex_db,
    "EIGHT_PALACES": mod.EIGHT_PALACES,
    "LIU_SHEN_MAP": mod.LIU_SHEN_MAP,
    "TIAN_GAN": mod.TIAN_GAN,
    "DI_ZHI": mod.DI_ZHI,
    "TIAN_GAN_WUXING": mod.TIAN_GAN_WUXING,
    "BRANCH_WUXING": mod.BRANCH_WUXING,
    "TRIGRAM_BINARY_MAP": mod.TRIGRAM_BINARY_MAP,
    "HEXAGRAM_PROBABILITIES": mod.HEXAGRAM_PROBABILITIES,
    "DEFAULT_SPECIAL_USERS": [
        {"username": "0", "password": "0", "expire_date": "2026/12/31"},
        {"username": "admin", "password": "admin123", "expire_date": "2025/10/26"},
        {"username": "test", "password": "test456", "expire_date": "2025/10/26"},
    ],
    "DEFAULT_API_KEY": "sk-5861282c4a9b443398947e9dc3a91547",
    "PROMPTS_WENDAO": grab_prompt("问道"),
    "PROMPTS_YIKANG": grab_prompt("易康"),
}

payload = json.dumps(data, ensure_ascii=False, indent=1)
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(
    "// AUTO-GENERATED by tools/extract_data.py — 请勿手工修改\n"
    "var LY_DATA = " + payload + ";\n"
    "if (typeof window !== 'undefined') window.LY_DATA = LY_DATA;\n"
    "if (typeof module !== 'undefined') module.exports = LY_DATA;\n",
    encoding="utf-8",
)
print(f"OK: {len(hex_db)} hexagrams -> {OUT}")
